name: 'Build dependency'

on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev]

jobs:
  build:
    name: Build on Node ${{ matrix.node }}
    runs-on: 'ubuntu-latest'

    strategy:
      matrix:
        node-version: [16.x, 18.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3.0.0
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Use NodeJs
        uses: actions/setup-node@v3.1.1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        uses: npm ci

      - name: Build project
        run: npm run build
